CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$ BEGIN
  CREATE TYPE "gender" AS ENUM ('Dama', 'Caballero', 'Unisex');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "admin_role" AS ENUM ('owner');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "migration_mode" AS ENUM ('dry_run', 'import', 'verify');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "migration_status" AS ENUM ('pending', 'running', 'validated', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "migration_item_status" AS ENUM ('imported', 'skipped', 'error', 'verified');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "admin_users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "email" text NOT NULL,
  "password_hash" text NOT NULL,
  "role" "admin_role" DEFAULT 'owner' NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "last_login_at" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "admin_users_email_unique" ON "admin_users" ("email");

CREATE TABLE IF NOT EXISTS "admin_sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "admin_user_id" uuid NOT NULL REFERENCES "admin_users"("id") ON DELETE CASCADE,
  "token_hash" text NOT NULL,
  "csrf_token_hash" text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "last_seen_at" timestamptz DEFAULT now() NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "admin_sessions_token_hash_unique" ON "admin_sessions" ("token_hash");

CREATE TABLE IF NOT EXISTS "categories" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "legacy_id" integer,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "categories_name_unique" ON "categories" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "categories_slug_unique" ON "categories" ("slug");

CREATE TABLE IF NOT EXISTS "products" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "legacy_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "legacy_document_id" text NOT NULL,
  "category_id" uuid REFERENCES "categories"("id") ON DELETE SET NULL,
  "legacy_type_label" text DEFAULT '' NOT NULL,
  "manufacturer" text DEFAULT '' NOT NULL,
  "brand" text DEFAULT '' NOT NULL,
  "gender" "gender" DEFAULT 'Unisex' NOT NULL,
  "price" numeric(10, 2) DEFAULT '0' NOT NULL CHECK ("price" >= 0),
  "sku" text,
  "color" text DEFAULT '' NOT NULL,
  "is_published" boolean DEFAULT false NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "source_created_at" timestamptz,
  "source_updated_at" timestamptz,
  "source_published_at" timestamptz,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "products_legacy_id_unique" ON "products" ("legacy_id");
CREATE UNIQUE INDEX IF NOT EXISTS "products_legacy_document_id_unique" ON "products" ("legacy_document_id");
CREATE UNIQUE INDEX IF NOT EXISTS "products_sku_unique" ON "products" ("sku");
CREATE INDEX IF NOT EXISTS "products_public_state_idx" ON "products" ("is_published", "is_active");
CREATE INDEX IF NOT EXISTS "products_category_idx" ON "products" ("category_id");
CREATE INDEX IF NOT EXISTS "products_gender_idx" ON "products" ("gender");
CREATE INDEX IF NOT EXISTS "products_type_idx" ON "products" ("legacy_type_label");

CREATE TABLE IF NOT EXISTS "product_variants" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "legacy_id" integer,
  "size_label" text NOT NULL,
  "quantity" integer DEFAULT 0 NOT NULL CHECK ("quantity" >= 0),
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "product_variants_product_size_unique" ON "product_variants" ("product_id", "size_label");

CREATE TABLE IF NOT EXISTS "product_images" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "legacy_id" integer,
  "legacy_url" text NOT NULL,
  "storage_pathname" text NOT NULL,
  "storage_url" text NOT NULL,
  "checksum" text,
  "mime_type" text NOT NULL,
  "byte_size" integer NOT NULL CHECK ("byte_size" > 0),
  "width" integer,
  "height" integer,
  "alt_text" text,
  "caption" text,
  "position" integer DEFAULT 0 NOT NULL CHECK ("position" >= 0),
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "deleted_at" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "product_images_product_legacy_url_unique" ON "product_images" ("product_id", "legacy_url");
CREATE UNIQUE INDEX IF NOT EXISTS "product_images_product_position_unique" ON "product_images" ("product_id", "position") WHERE "deleted_at" IS NULL;

CREATE TABLE IF NOT EXISTS "migration_runs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "mode" "migration_mode" NOT NULL,
  "status" "migration_status" DEFAULT 'pending' NOT NULL,
  "source_url" text NOT NULL,
  "started_at" timestamptz DEFAULT now() NOT NULL,
  "finished_at" timestamptz,
  "expected_products" integer,
  "imported_products" integer DEFAULT 0 NOT NULL,
  "expected_images" integer,
  "imported_images" integer DEFAULT 0 NOT NULL,
  "error_count" integer DEFAULT 0 NOT NULL CHECK ("error_count" >= 0),
  "report_path" text
);

CREATE TABLE IF NOT EXISTS "migration_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "run_id" uuid NOT NULL REFERENCES "migration_runs"("id") ON DELETE CASCADE,
  "entity_type" text NOT NULL,
  "source_id" text NOT NULL,
  "target_id" text,
  "status" "migration_item_status" NOT NULL,
  "source_checksum" text,
  "message" text,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "migration_items_run_idx" ON "migration_items" ("run_id");
CREATE INDEX IF NOT EXISTS "migration_items_source_idx" ON "migration_items" ("entity_type", "source_id");
